---
- name: Copy DevTools installer
  copy:
    src: "{{ item }}"
    dest: "/tmp/{{ item | basename }}"
    mode: "0644"
    force: yes
  with_fileglob: rpms_development_tools/*.rpm

- name: Install DevTools from a local rpm file 
  yum:
    name: "/tmp/{{ item | basename }}"
    state: present
  with_fileglob: rpms_development_tools/*.rpm

- name: Copy installer which installation of OpenCV requires
  copy:
    src: "{{ item }}"
    dest: "/tmp/{{ item | basename }}"
    mode: "0644"
    force: yes
  with_fileglob: rpms_opencv/*.rpm

- name: Install packages from a local rpm file 
  yum:
    name: "/tmp/{{ item | basename }}"
    state: present
  with_fileglob: rpms_opencv/*.rpm

